GET http://localhost:5280/books

###

GET http://localhost:5280/books/2

###

POST http://localhost:5280/books
Content-Type: application/json

{
    "title": "Den eviga brudtärnan",
    "author": "Lindsey Kelk",
    "genre": "Romance",
    "releaseYear": 2024,
    "language": "Swedish",
    "description": "Att vara brudtärna för min bästa vän är som att rida en berg-och dalbana: spännande, skrämmande och ibland vill jag bara hoppa av. Men trots bridezilla-tendenser och en brudgum med tveksamma vanor, är jag här för att stötta och fira kärleken. Och kanske, bara kanske, hitta lite kärlek själv på vägen."
}

###
PUT http://localhost:5280/books/3
Content-Type: application/json

{
    "title": "Code Complete",
    "author": "Steve McConnell",
    "genre": "Education",
    "releaseYear": 2004,
    "language": "English",
    "description": "For more than a decade, Steve McConnell, one of the premier authors and voices in the software community, has helped change the way developers write code--and produce better software. Now his classic book, CODE COMPLETE, has been fully updated and revised with best practices in the art and science of constructing software. Whether you're a new developer seeking a sound introduction to the practice of software development or a veteran exploring strategic new approaches to problem solving, you'll find a wealth of practical suggestions and methods for strengthening your skills."
}

###

DELETE http://localhost:5280/books/3